name: Quality Assurance

'on':
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3.5.2
            -
                uses: ScribeMD/docker-cache@0.3.3
                with:
                    key: ${{ runner.os }}-docker-${{ hashFiles('Makefile', 'composer.json') }}
            -
                run: make lint
